services:
  redis:
    image: redis:alpine
    container_name: forensis_redis

  forensis:
    build: .
    container_name: forensis
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./instance:/app/instance

  celery_worker:
    build: .
    container_name: forensis_worker
    command: celery -A app.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./instance:/app/instance
