#!/usr/bin/env python3
"""Check Alembic migration drift against SQLAlchemy models.

Behavior:
1) Apply all migrations (`upgrade head`) to target DB.
2) Run `alembic check` to detect pending autogenerated ops.

Exit code non-zero when drift is detected.
"""

from __future__ import annotations

import os
import sys

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect


def main() -> int:
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    alembic_ini = os.path.join(repo_root, "alembic.ini")
    if not os.path.isfile(alembic_ini):
        print("alembic.ini not found", file=sys.stderr)
        return 2

    db_uri = (os.getenv("FORENSIS_DB_URI", "") or "").strip()
    if not db_uri:
        db_uri = "sqlite:///instance/ci_migration_check.db"
        os.environ["FORENSIS_DB_URI"] = db_uri

    if db_uri.startswith("sqlite:///"):
        db_path = db_uri.replace("sqlite:///", "", 1)
        if not os.path.isabs(db_path):
            db_path = os.path.join(repo_root, db_path)
        os.makedirs(os.path.dirname(db_path), exist_ok=True)

    cfg = Config(alembic_ini)
    cfg.set_main_option("script_location", os.path.join(repo_root, "migrations"))
    cfg.set_main_option("sqlalchemy.url", db_uri)

    try:
        engine = create_engine(db_uri)
        inspector = inspect(engine)
        table_names = set(inspector.get_table_names())
        has_version = "alembic_version" in table_names
        managed_core = {
            "group",
            "users",
            "analysis_history",
            "system_setting",
            "dfir_case",
            "artifact",
            "analysis_job",
            "finding",
            "rule_match",
            "timeline_event",
        }
        if (not has_version) and (table_names & managed_core):
            print("[migration] legacy schema detected without alembic_version, stamping head")
            command.stamp(cfg, "head")

        print(f"[migration] upgrade head on {db_uri}")
        command.upgrade(cfg, "head")
        print("[migration] running alembic check")
        command.check(cfg)
    except Exception as exc:
        print(f"[migration] drift check failed: {exc}", file=sys.stderr)
        return 1

    print("[migration] drift check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
